import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import styles from "./cookies.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";
import { AiOutlineCheckCircle } from "react-icons/ai";
import Link from "next/link";


export default function SolucoesInovadoras() {

  return (
    <div className={styles.main}>
      <Head>
        <title>SGP - Soluções em Gestão Público</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
      </Head>
      <Navbar />
        <div className={styles.content}>
            <div className={styles.bluredBall}></div>
            <div className={styles.headerContent}>
            <h1>Política de <em>Cookies</em></h1>
            <hr />
            </div>
        </div>
        <div className={styles.pageSize}>
            <div className={styles.realContent}>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>I. Introdução e escopo</h3>
                        <ul>
                            <li>A presente <b>Política de <em>Cookies</em></b> aplica-se ao site da <b>SGP - Soluções em Gestão Pública</b>, de propriedade da <b>SGP - Soluções em Gestão Pública</b>, e visa proporcionar uma experiência ainda mais transparente em nosso site, explicando o conceito de <em>Cookies</em>, como os utilizamos para melhorar sua navegação e, ainda, as possibilidades de customização do uso.</li>
                            <li>Caso não concorde com o uso de <em>Cookies</em> da forma apresentada, você poderá:</li>
                            <li>⚙️ ajustar as configurações de seu navegador de internet para não permitir o uso de <em>Cookies</em></li>
                            <li>⚙️ não acessar o site.</li>
                            <li>Lembramos que desabilitar o uso de <em>Cookies</em> poderá impactar sua experiência ao navegar no site.</li>
                            <li>Recomendamos também a leitura da nossa <Link href={"politica-privacidade"}>Política de Privacidade</Link>, na qual trazemos à você mais informações sobre nosso compromisso com a sua privacidade e a proteção dos seus dados pessoais.</li>
                        </ul>
                    </div>
                </div> <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>II. O QUE SÃO <em>COOKIES</em>?</h3>
                        <ul>
                          <li><em>Cookies</em> são pequenos arquivos digitais em formato de texto que são armazenados no seu dispositivo, como: computador, smartphone, table, etc., pelo navegador de internet e que guardam informações relacionadas às suas preferências, como idioma preferido, localização, recorrência das suas sessões, e outras variáveis que os desenvolvedores consideram relevantes para tornar a sua experiência muito mais eficiente.</li>
                        </ul>
                    </div>
                </div>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>III. PARA QUE SERVEM OS <em>COOKIES</em>?</h3>
                        <ul>
                          <li>Os <em>Cookies</em> servem para aprimorar a sua experiência, tanto em termos de performance, como em termos de usabilidade, uma vez que os conteúdos disponibilizados serão direcionados às suas necessidades e expectativas.</li>
                          <li>Também poderão ser utilizados para compilar estatísticas anônimas e agregadas que permitem entender como você utiliza o site, bem como para aprimorar suas estruturas e conteúdo. Por serem estatísticas anônimas, não é possível identificá-lo pessoalmente por meio desses dados.</li>
                          <li>A utilização de <em>Cookies</em> é algo muito comum em qualquer plataforma digital atualmente. O seu uso não prejudica de forma alguma os dispositivos em que são armazenados.</li>
                        </ul>
                    </div>
                </div>

                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>IV. QUE TIPO DE <em>COOKIES</em> UTILIZAMOS</h3>
                        <ul>
                          <li>Nós utilizamos <em>Cookies</em> próprios e de terceiros no site, os quais podem ser classificados quanto à sua temporalidade:</li>
                          <li><b>1. <em>Cookies</em> de Sessão:</b> são os <em>Cookies</em> temporários que permanecem arquivados até que você saia do site ou encerre o navegador.</li>
                          <li><b>2. <em>Cookies</em> Persistentes:</b> são os <em>Cookies</em> que ficam armazenados no seu dispositivo até que sejam excluídos. O tempo que o <em>Cookie </em>permanecerá no dispositivo depende do seu tempo de vida e das configurações do seu navegador de internet.</li>
                          <li>Os <b> <em>Cookies</em> de Sessão ou Persistentes: </b> ainda podem ser categorizados de acordo com a sua função:</li>
                          <li><b>1. <em>Cookies</em> Estritamente Necessários:</b> permitem a navegação e utilização das aplicações, bem como o acesso a áreas seguras do site. Sem estes <em>Cookies</em>, o site não funciona corretamente.</li>
                          <li><b>2. <em>Cookies</em> de Funcionalidade:</b> são utilizados para assegurar a disponibilização de funcionalidades adicionais do site ou para guardar as preferências definidas pelo usuário ao navegar na internet, sempre que utilizar o mesmo dispositivo.</li>
                          <li><b>3. <em>Cookies</em> de Publicidade: </b>coletam as informações de sua visita em nosso site para que as propagandas nele dispostas sejam mais relevantes para você e de acordo com os seus interesses. Geralmente estão atrelados a <em>Cookies</em> de propriedade de terceiros. Caso você desabilite estes <em>cookies</em>, note que você ainda visualizará as publicidades, mas elas serão personalizadas às suas preferências.</li>
                        
                        </ul>
                    </div>
                </div>

                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>V. É POSSÍVEL CONTROLAR OU EXCLUIR <em>COOKIES</em>?</h3>
                        <ul>
                          <li>Para que nosso site opere corretamente, você deverá habilitar o uso dos <em>Cookies</em>. Caso decida não os habilitar, você ainda poderá navegar no site, mas algumas funcionalidades não estarão disponíveis.</li>
                          <li>Lembrando que a maioria dos navegadores de internet é configurada para aceitar automaticamente os <em>Cookies</em>.</li>
                          <li>Você pode alterar as configurações para bloquear o uso de <em>Cookies</em> ou alertá-lo quando um <em>Cookie </em>estiver sendo enviado para o seu dispositivo. Existem várias formas de gerenciar <em>Cookies</em>, consulte as instruções de seu navegador.</li>
                          <li>Caso você utilize dispositivos diferentes para acessar o site, deverá assegurar-se de que cada navegador, de cada dispositivo, esteja ajustado para atender às suas preferências em relação aos <em>Cookies</em>.</li>
                          <li>Para que você possa, de forma simples e intuitiva, gerir suas preferências a partir do seu navegador, poderá utilizar um dos links abaixo:</li>
                          <li>📓 Para mais informações sobre gestão de <em>Cookies</em> no Firefox, <Link href={"https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop?redirectlocale=en-US&redirectslug=enable-and-disable-cookies-website-preferences"}>clique aqui</Link>;</li>
                          <li>📓 Para mais informações sobre gestão de <em>Cookies</em> no Chrome, <Link href={"https://support.google.com/chrome/answer/95647?hl=en"}>clique aqui</Link>;</li>
                          <li>📓 Para mais informações sobre gestão de <em>Cookies</em> no Internet Explorer, <Link href={"https://support.microsoft.com/pt-pt/windows/eliminar-e-gerir-cookies-168dab11-0753-043d-7c16-ede5947fc64d"}>clique aqui</Link>;</li>
                          <li>📓 Para mais informações sobre gestão de <em>Cookies</em> no Safari, <Link href={"https://support.apple.com/pt-br/guide/safari/sfri11471/mac"}>clique aqui</Link>;</li>
                          <li>📓 Para mais informações sobre gestão de <em>Cookies</em> no Opera, <Link href={"https://help.opera.com/en/latest/security-and-privacy/#privateWindow"}>clique aqui</Link>;</li>
                          <li>📓 Para mais informações sobre gestão de <em>Cookies</em> no Microsoft Edge, <Link href={"https://support.microsoft.com/pt-br/microsoft-edge/navegação-inprivate-no-microsoft-edge-e6f47704-340c-7d4f-b00d-d0cf35aa1fcc"}>clique aqui</Link>.</li>
                        </ul>
                    </div>
                </div>

                <div className={styles.topico}>
                    <div className={styles.parteN}>
                      <h3>VI. INFORMAÇÕES DETALHADAS SOBRE OS <em>COOKIES</em></h3>
                      <ul>
                        <li>Apresentamos abaixo os detalhes sobre o uso dos <em>Cookies</em> no site, bem como as suas finalidades:</li>
                        <li><b>1. <em>Cookies</em> estritamente necessários:</b> Nome do Cookie, Finalidade, Validade, Tipo PHPSESSID, preserva o estado da sessão do usuário nas solicitações de página.</li>
                        <li><b>2. <em>Cookies</em> Analíticos:</b> Nome do Cookie, Finalidade, Validade, Tipo _ga, registra um ID único que é usado para gerar dados estatísticos sobre como o visitante usa a plataforma - 2 anos - Persistente _gat usado pelo Google Analytics para controlar a taxa de solicitação - 1 dia - Persistente _gid, registra um ID único que é usado para gerar dados estatísticos sobre como o visitante usa a plataforma - 1 dia - Persistente.</li>
                        <li><b>3. <em>Cookies</em> de Publicidade</b></li>
                      </ul>
                      <div style={{textAlign: "center",  marginBlock: "30px"}}>
                        <p>✔ Nome do <em>Cookie </em></p>
                        <p>📌 Finalidade </p>
                        <p>📅 Validade </p>
                        <p>🏁 Tipo</p>
                      </div>
                      <p>✔ <b>IDE</b> 📌 Usado pelo Google DoubleClick para registrar e relatar as ações do usuário do site após visualizar ou clicar em um dos anúncios do anunciante com o objetivo de medir a eficácia de um anúncio e apresentar anúncios direcionados ao usuário. 📅 1 ano 🏁 Persistente</p>
                      <p>✔ <b>test_<em>cookie </em></b>📌 Usado para verificar se o navegador do usuário suporta <em>cookies</em>. 📅 1 dia 🏁 Persistente</p>
                      <p>✔ <b>VISITOR_INFO1_LIVE</b> 📌 Tenta estimar a largura de banda dos usuários em páginas com vídeos integrados do YouTube. 📅 179 dias 🏁 Persistente</p>
                      <p>✔ <b>YSC</b> 📌 Registra um ID único para manter estatísticas de quais vídeos do YouTube o usuário tem visto. 📅 🏁 Sessão</p>
                      <p>✔ <b>yt.innertube::nextId</b> 📌 Registra um ID único para manter estatísticas de quais vídeos do YouTube o usuário tem visto. 📅 🏁 Persistente</p>
                      <p>✔ <b>yt.innertube::requests</b> 📌 Registra um ID único para manter estatísticas de quais vídeos do YouTube o usuário tem visto. 📅 🏁 Persistente</p>
                      <p>✔ <b>yt-remote-cast- installed</b> 📌 Armazena as preferências do reprodutor de vídeo do usuário usando o vídeo incorporado do YouTube. 📅 🏁 Sessão</p>
                      <p>✔ <b>yt-remote- connected-devices</b> 📌 Armazena as preferências do reprodutor de vídeo do usuário usando o vídeo incorporado do YouTube. 📅 🏁 Persistente</p>
                      <p>✔ <b>yt-remote-device-id</b> 📌 Armazena as preferências do reprodutor de vídeo do usuário usando o vídeo incorporado do YouTube. 📅 🏁 Persistente</p>
                      <p>✔ <b>yt-remote-fast- check-period</b> 📌 Armazena as preferências do reprodutor de vídeo do usuário usando o vídeo incorporado do YouTube. 📅 🏁 Sessão</p>
                      <p>✔ <b>yt-remote-session- app</b> 📌 Armazena as preferências do reprodutor de vídeo do usuário usando o vídeo incorporado do YouTube. 📅 🏁 Sessão</p>
                      <p>✔ <b>yt-remote-session- name</b> 📌 Armazena as preferências do reprodutor de vídeo do usuário usando o vídeo incorporado do YouTube. 📅 🏁 Sessão</p>
                    </div>
                </div>

                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3></h3>
                        <ul>
                          <li></li>
                          <li></li>
                          <li></li>
                          <li></li>
                          <li></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
        <FooterCompleto />
    </div>
  );
}
