import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import styles from "./termos.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";
import { AiOutlineCheckCircle } from "react-icons/ai";

export default function SolucoesInovadoras() {

  return (
    <div className={styles.main}>
      <Head>
        <title>SGP - Soluções em Gestão Público</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
      </Head>
      <Navbar />
        <div className={styles.content}>
            <div className={styles.bluredBall}></div>
            <div className={styles.headerContent}>
            <h1><b>Política de Privacidade</b></h1>
            <hr />
            </div>
        </div>
        <div className={styles.pageSize}>
            <div className={styles.realContent}>
                <h2>Termo de Consentimento para Clientes, Fornecedores e Parceiros</h2>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>I. INFORMAÇÕES GERAIS</h3>
                        <ul>
                            <li>A presente <b>Política de Privacidade</b> foi elaborada nos moldes da <b>Lei n. 12.965/2014 (Marco Civil da Internet)</b> e <b>Lei n. 13.709/2018 (Lei Geral de Proteção de Dados)</b>, para informar o conjunto de regras para garantir a confidencialidade, a integridade e a disponibilidade de <em>dados pessoais</em> coletados, pelo site, redes sociais, correio eletrônico, telefone ou WhatsApp, com o fornecimento de nome ou razão social, número de telefone, celular, e-mail, endereço, documento de identificação, CEP e nome de contato.</li>
                            <li>Em decorrência de eventual atualização normativa esta <b>Política de Privacidade</b> poderá ser revisada e atualizada, razão pela qual se convida o Titular a consultar periodicamente esta seção.</li>
                        </ul>
                    </div>
                </div>

                <div className={styles.topico}>
                  <div className={styles.parteN}>
                        <h3>II. RESPONSÁVEL PELO TRATAMENTO</h3>
                        <ul>
                            <li>A <b>SGP - Soluções em Gestão Pública</b>, na qualidade de Controladora, promove o tratamento dos <em>dados pessoais</em> de seus funcionários, colaboradores terceirizados, fornecedores, clientes, visitantes e demais stakeholders para operar seus negócios.</li>
                        </ul>
                    </div>
                </div>

                <div className={styles.topico}>
                <div className={styles.parteN}>
                        <h3>III. TIPOS DE DADOS TRATADOS</h3>
                        <ul>
                            <li>Os <em>dados pessoais</em> tratados são aqueles necessários para que o titular possa realizar consultas ou cadastro em nossos canais de comunicação seja pelo site, redes sociais, telefone, correio eletrônico ou WhatsApp com o fornecimento de nome ou razão social, número de telefone, celular, e-mail, endereço e documento de identificação.</li>
                            <li>Para a execução de contrato de compra e venda ou de prestação de serviços eventualmente firmado entre a <b>SGP - Soluções em Gestão Pública</b> e o titular, poderão ser coletados e armazenados outros dados incluindo o teor de eventuais comunicações tidas com o titular, no registro de acesso conforme <b>artigo 15º da lei 12.685 do Marco Civil da Internet.</b></li>
                            <li>O endereço de e-mail ou físico cadastrado pelo titular que optar por se inscrever em nossa Newsletter será coletado e armazenado até que o titular solicite seu descadastro por e-mail: <b>valdir.moda@sgpsolucoes.com.br.</b></li>
                            <li>Os dados podem ser tratados na forma de cópias e digitalização de documentos em papel, fotos dos mesmos e também na forma de dados em softwares e sistemas digitais.</li>
                        </ul>
                    </div>
                  </div>
  
                  <div className={styles.topico}>
                    <div className={styles.parteN}>
                      <h3>IV. FINALIDADES DO TRATAMENTO DOS <em>DADOS PESSOAIS</em></h3>
                      <ul>
                          <li>Os <em>dados pessoais</em> do titular coletados pela <b>SGP - Soluções em Gestão Pública</b>, têm por finalidade facilitar, agilizar e cumprir os compromissos estabelecidos com o titular e a fazer cumprir as solicitações realizadas por meio do preenchimento de formulários, inclusive para campanhas de marketing e mailing.</li>
                          <li>Os <em>dados pessoais</em> poderão ser utilizados também com uma finalidade comercial, para personalizar o conteúdo oferecido ao titular, bem como para dar subsídio à <b>SGP - Soluções em Gestão Pública</b> para a melhora da qualidade e funcionamento de seus serviços.</li>
                          <li>Os dados de cadastro serão utilizados ainda para permitir o acesso do titular a determinados conteúdos do site, exclusivos para titulares cadastrados.</li>
                          <li>Os dados podem ser tratados na forma de cópias e digitalização de documentos em papel, fotos dos mesmos e também na forma de dados em softwares e sistemas digitais.</li>
                          <li>A coleta de dados relacionados ou necessários à execução de um contrato de compra e venda ou de prestação de serviços eventualmente firmado com o titular terá a finalidade de conferir às partes segurança jurídica, além de facilitar e viabilizar a conclusão do negócio.</li>
                          <li>O tratamento de <em>dados pessoais</em> para finalidades não previstas nesta <b>Política de Privacidade</b> somente ocorrerá mediante comunicação prévia ao titular, sendo que, em qualquer caso, os direitos e obrigações aqui previstos permanecerão aplicáveis.</li>
                      </ul>
                    </div>
                  </div>
  
                
                    
                  <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>V. DIREITOS DO TITULAR DOS DADOS</h3>
                        <ul>
                          <li>O Titular deverá fornecer somente seus <em>dados pessoais</em>, a fim de resguardar e proteger os direitos de terceiros.</li>
                          <li>Caso o Titular tenha dado consentimento à <b>SGP - Soluções em Gestão Pública</b> para tratar seus dados poderá:</li>
                          <li><b>1. </b> consultar seus dados sob tratamento;</li>
                          <li><b>2. </b> solicitar a retificação dos <em>dados pessoais</em> inexatos que lhe digam respeito;</li>
                          <li><b>3. </b> requerer a revogação do consentimento e via de consequência os dados serão apagados. Os serviços e benefícios que dependem desta informação serão consequentemente interrompidos pela <b>SGP - Soluções em Gestão Pública</b>.</li>
                          <li>Dados que a <b>SGP - Soluções em Gestão Pública</b> deve reter por exigências legais não poderão ser apagados.</li>
                          <li>O Titular poderá exercer seus direitos de consentimento, consulta, retificação ou revogação sempre por escrito, em formulário eletrônico ou e-mail.</li>
                        </ul>
                    </div>
                  </div>

                  <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>VI. BASES LEGAIS PARA TRATAMENTO DOS DADOS</h3>
                        <ul>
                          <li>As bases legais que permitem à <b>SGP - Soluções em Gestão Pública</b> tratar <em>dados pessoais</em> são:</li>
                          <li><b>1.</b> Cumprimento de obrigação legal ou regulatória por <b>SGP - Soluções em Gestão Pública</b>;</li>
                          <li><b>2.</b> Quando o titular dos <em>dados pessoais</em> é parte em contrato ou seus <em>dados pessoais</em> são necessários para execução de procedimentos preliminares para se firmar o contrato;</li>
                          <li><b>3.</b> Para exercício regular de direitos em processo administrativo, judicial ou arbitral, prezando sempre que possível pelo pedido de segredo de justiça quando envolver dado pessoal;</li>
                          <li><b>4.</b> Para a proteção da vida ou da segurança física do titular;</li>
                          <li><b>5.</b> Para proteção da saúde, exclusivamente em procedimento realizado por profissionais de saúde, serviços de saúde ou autoridade sanitária;</li>
                          <li><b>6.</b> Por interesse legítimo da <b>SGP - Soluções em Gestão Pública</b> ou de terceiros;</li>
                          <li><b>7.</b> Para a proteção do crédito.</li>
                          <li>O tratamento de dados que não se enquadre nas situações anteriores a <b>SGP - Soluções em Gestão Pública</b> solicitará, consentimento formal do titular dos <em>dados pessoais</em>.</li>
                        </ul>
                    </div>
                  </div>

                  <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>VII. COMPARTILHAMENTO DE DADOS PESSOAIS</h3>
                        <ul>
                          <li>Os <em>dados pessoais</em> coletados poderão ser compartilhados com empresas parceiras, clientes, prestadores de serviços e fornecedores no, Brasil e no exterior, conforme a necessidade e sempre com o propósito de dar andamento aos negócios da <b>SGP - Soluções em Gestão Pública</b>.</li>
                        </ul>
                    </div>
                  </div>

                  <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>VIII. USO DE COOKIES</h3>
                        <ul>
                          <li>Cookies são elementos minúsculos de dados que um site pode enviar a um navegador, que poderão ser armazenados no disco rígido visando melhorar a experiência on-line, enquanto o titular visita o site. Não contêm informações pessoais identificáveis.</li>
                          <li>Para acessar os sistemas de informação dos meios digitais da <b>SGP - Soluções em Gestão Pública</b>, pode ser necessário aceitar cookies nos dispositivos. A negativa de aceitar os cookies pode reduzir ou inibir as funcionalidades dos serviços disponibilizados.</li>
                          <li>As informações eventualmente armazenadas em cookies que permitam identificar um Titular são consideradas <em>dados pessoais</em>. Dessa forma, todas as regras previstas nesta <b>Política de Privacidade</b> também são aplicáveis.</li>
                        </ul>
                    </div>
                  </div>

                  <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>IX. DADOS DE CRIANÇAS E ADOLESCENTES</h3>
                        <ul>
                          <li>O consentimento dos relativamente ou absolutamente incapazes, especialmente de crianças menores de 16 (dezesseis) anos, apenas poderá ser feito, respectivamente, se devidamente assistidos ou representados.</li>
                          <li>Poderão ainda ser coletados <em>dados pessoais</em> necessários para a execução e cumprimento dos serviços contratados pelo Titular nos nossos canais de comunicação.</li>
                          <li><em>Dados pessoais</em> de crianças e adolescentes ainda podem ser usados pela <b>SGP - Soluções em Gestão Pública</b> para atividades beneficentes, educativas, ações internas de confraternização, atividades curriculares, jovem aprendiz e controle de acesso físico.</li>
                        </ul>
                    </div>
                  </div>

                  <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>X. INDICAÇÃO DO DPO E DE CANAIS DE CONTATO</h3>
                        <ul>
                          <li>A indicação do DPO é feita através de nomeação formal pela Diretoria. O DPO é responsável por acolher as requisições dos titulares dos <em>dados pessoais</em> e dar encaminhamento às solicitações, sempre observando as bases legais e a legislação pertinente.</li>
                          <li>Solicitações ao DPO devem ser enviadas ao e-mail indicado ao final deste documento ou em formulário em papel a ele endereçado e disponibilizado pela <b>SGP - Soluções em Gestão Pública</b>.</li>
                        </ul>
                    </div>
                  </div>

                  <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>XI. TEMPO DE RETENÇÃO DOS <em>DADOS PESSOAIS</em></h3>
                        <ul>
                          <li>Quando não definido por lei, o tempo de retenção dos <em>dados pessoais</em> e dos documentos ou arquivos que os contém é definido conforme os propósitos da controladora.</li>
                        </ul>
                    </div>
                  </div>

                  <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>XII. SEGURANÇA DA INFORMAÇÃO</h3>
                        <ul>
                          <li>Os <em>dados pessoais</em> obtidos na forma física ou digital são protegidas com medidas físicas, técnicas e administrativas de segurança para reduzir riscos de perda, mau uso e acesso não autorizado, divulgação e alteração, tais como firewalls e criptografia de dados, controles de acesso físico a data centers, além de controles de autorização de acesso à informação.</li>
                          <li>O site utiliza certificado SSL (Secure Socket Layer) que garante que os <em>dados pessoais</em> se transmitam de forma segura e confidencial, totalmente cifrada ou encriptada entre o servidor e o Titular.</li>
                          <li>A <b>SGP - Soluções em Gestão Pública</b> se exime de responsabilidade por culpa exclusiva de terceiro, como em caso de ataque de hackers ou crackers, ou culpa exclusiva do Titular, como no caso em que ele mesmo transfere seus dados a terceiro.</li>
                          <li>Caso ocorra algum tipo de violação da segurança dos <em>dados pessoais</em> o Titular será devidamente comunicado em prazo adequado.</li>
                          <li>A <b>SGP - Soluções em Gestão Pública</b> não vende e nem aluga os <em>dados pessoais</em> coletados para terceiros em nenhuma hipótese, inclusive para fins de marketing.</li>
                        </ul>
                    </div>
                  </div>

                  <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>XIII. DISPOSIÇÕES FINAIS</h3>
                        <ul>
                          <li>Esta <b>Política de Privacidade</b> bem como os demais documentos que a complementam encontra-se disponíveis para consulta no site da <b>SGP - Soluções em Gestão Pública</b>, e em caso de indisponibilidade, podem ser solicitados ao DPO.</li>
                          <li>Dúvidas relativas a <b>Política de Privacidade</b> devem ser encaminhada ao DPO por meio do e-mail <b>valdir.moda@sgpsolucoes.com.br.</b></li>
                        </ul>
                    </div>
                  </div>

                  <div className={styles.segurancaDados}>
                    <p>Cifrada: Alteração da mensagem original, por meio de mudança de ordem, aparência, tipo de letras ou fonemas, de modo a torná-la ininteligível para quem a interceptar e não souber como reproduzir a mensagem original (decifração ou decriptação).</p>
                    <p>Criptografia: É converter um arquivo num codigo secreto, com o intuito de que as informações nele contidas não possam ser lidas até serem decodificadas.</p>
                    <p>Encriptar: Arquivo em código secreto</p>
                    <p>ANPD - Autoridade Nacional de Proteção de Dados.</p>
                    <p>DPO - Data Protection Officer - Encarregado da Proteção de Dados.</p>
                    <p>LGPD - Lei Geral de Proteção de Dados.</p>
                    <p>Navegador: Um navegador web leva você a qualquer lugar na internet, permitindo ver textos, imagens e vídeos de qualquer lugar do mundo.</p>
                    <p>Plataforma Digital: É um lugar para a troca de informações, bens ou serviços entre produtores e consumidores, além da participação de uma comunidade.</p>
                </div>
                <p className={styles.revisao}>Este Termo de Consentimento da Privacidade foi revisado em 15 de Dezembro de 2021.</p>
            </div>
        </div>
        <FooterCompleto />
    </div>
  );
}
