import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import styles from "./politica.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";
import { AiOutlineCheckCircle } from "react-icons/ai";


export default function SolucoesInovadoras() {

  return (
    <div className={styles.main}>
      <Head>
        <title>SGP - Soluções em Gestão Público</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
      </Head>
      <Navbar />
        <div className={styles.content}>
            <div className={styles.bluredBall}></div>
            <div className={styles.headerContent}>
            <h1>Termo de Consentimento da Privacidade</h1>
            <hr />
            </div>
        </div>
        <div className={styles.pageSize}>
            <div className={styles.realContent}>
                <h2>Termo de Consentimento para Clientes, Fornecedores e Parceiros</h2>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>I. Introdução e escopo</h3>
                        <ul >
                            <li>A <b>SGP - Soluções em Gestão Pública</b> tem o compromisso de processar dados pessoais de forma responsável e em conformidade com as leis de proteção de dados aplicáveis em todos os países nos quais opera.</li>
                            <li>Este Termo de Privacidade para Clientes, Fornecedores e Parceiros de Negócios descreve os tipos de dados pessoais que a <b>SGP - Soluções em Gestão Pública</b> faz tratamento e como a <b>SGP - Soluções em Gestão Pública</b> usa os dados pessoais, com quem a <b>SGP - Soluções em Gestão Pública</b> compartilha os dados pessoais e os direitos que você, como titular dos dados, tem em relação ao uso dos dados pessoais pela <b>SGP - Soluções em Gestão Pública</b>.</li>
                            <li><em>Este Termo também descreve como você pode nos contatar sobre nossas práticas de proteção de dados.</em></li>
                        </ul>
                    </div>
                </div>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>II. Informações de Contato</h3>
                        <ul >
                            <li>A <b>SGP - Soluções em Gestão Pública</b> nomeou como DPO um colaborador responsável pela proteção dos dados pessoais, podendo ser contatado no endereço de e-mail: valdir.moda@sgpsolucoes.com.br.</li>
                            <li>O DPO é responsável por aceitar reclamações e comunicações dos titulares dos dados em relação aos dados pessoais, prestar esclarecimentos, receber comunicações da Autoridade Nacional de Proteção de Dados - ANPD.</li>
                        </ul>
                    </div>
                </div>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>III. Dados Pessoais Tratados</h3>
                        <ul >
                            <li>O fornecimento de <em>dados pessoais</em> é um requisito necessário para as relações entre a <b>SGP - Soluções em Gestão</b> Pública, Clientes, Fornecedores e Parceiros de Negócio. Os <em>dados pessoais</em> tratados limitam-se aos dados necessários para cumprir a finalidade para a qual tais <em>dados pessoais</em> são coletados.</li>
                            <li className={styles.coloredTitle}>1. Clientes, Fornecedores e Parceiros de Negócios</li>
                            <li>A <b>SGP - Soluções em Gestão Pública</b> poderá tratar os seguintes <em>dados pessoais</em>: nome, endereço, número de telefone residencial, número de celular, endereço de e-mail, Registro Geral, Cadastro de Pessoas Físicas, informações bancárias, genero, idade, data e local de nascimento, nacionalidade, ocupação, cargo, endereço postal comercial, número de telefone comercial, número de fax comercial, endereço de e- mail comercial, número da placa do carro, carteira de motorista, fotos e vídeos.</li>
                            <li className={styles.coloredTitle}>2. Candidato a vaga de emprego</li>
                            <li>A <b>SGP - Soluções em Gestão Pública</b> poderá tratar os seguintes <em>dados pessoais</em>: nome completo, gênero, endereço completo, número de telefone e celular, endereço de e-mail, informações bancárias, profissão e data de nascimento.</li>
                            <li>A <b>SGP - Soluções em Gestão Pública</b> não coletará <em>dados pessoais</em> se tal coleta for proibida pelas leis de proteção de dados aplicáveis.</li>
                        </ul>
                    </div>
                </div>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>IV. Finalidades do processamento de dados e base legal</h3>
                        {/* from here */}
                        <ul >
                            <li>O tratamento dos dados pessoais será realizado de acordo com as leis de proteção de dados aplicáveis, apenas para fins limitados, explícitos e legítimos e com as disposições estabelecidas neste Termo de Privacidade.</li>
                            <li>Os dados pessoais serão tratados pelas razões e bases legais descritas abaixo, a fim de cumprir com as obrigações assumidas pela <span style={{fontWeight: "bold"}}>SGP - Soluções em Gestão Pública</span>, resultantes da legislação aplicável e obrigações legais.</li>
                            <hr />
                            <li className={styles.coloredTitleSpecial}>1. Clientes - <em>Dados Pessoais</em></li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Finalidade Base Legal</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Gerenciar relacionamentos comerciais, atendimento de pedidos, pagamento e faturamento de bens e serviços, contatando o cliente. 📓 Obrigação contratual, Interesse legítimo.</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Realizar operações promocionais, marketing direto para promover a posição da <b>SGP - Soluções em Gestão Pública</b> no mercado. 📓 Interesse legítimo, Consentimento.</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Detectar e prevenir fraude para garantir a segurança e integridade da <b>SGP - Soluções em Gestão Pública</b>. 📓 Cumprimento de obrigação legal, Exercício regular de direitos, Interesse legítimo</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Garantir a segurança e integridade da <b>SGP - Soluções em Gestão Pública</b> e dos indivíduos. 📓 Para a proteção da vida ou incolumidade física do titular ou de Terceiro.</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Responder os procedimentos legais ou de órgãos administrativos/entidades reguladoras. Cumprir as obrigações legais e/ou investigações regulatórias, auxiliando a <b>SGP - Soluções em Gestão Pública</b> no contexto de qualquer litígio ou arbitragem e protegendo a <b>SGP - Soluções em Gestão Pública</b> contra lesões, roubo, responsabilidade legal, fraude, abuso ou outra conduta imprópria. 📓 Cumprimento de obrigação contratual, Interesse legítimo.</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Gerenciar transações da <b>SGP - Soluções em Gestão Pública</b> (por exemplo, fusão ou aquisição) para conduzir negociações comerciais da <b>SGP - Soluções em Gestão Pública</b>. 📓 Cumprimento de obrigação legal e regulatória,</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Gerenciar as operações da <b>SGP - Soluções em Gestão Pública</b>, incluindo a operação e monitoramento do bom funcionamento e segurança dos sistemas de TI da <b>SGP - Soluções em Gestão Pública</b> para garantir sua proteção e segurança. 📓 Cumprimento de obrigação contratual, Interesse legítimo.</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Gerenciar incidentes de saúde e segurança. 📓Para a proteção da vida ou da incolumidade física do titular ou de Terceiro e Cumprimento de obrigação legal e regulatória</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Gerenciar entregas e remessas de produtos para administrar os negócios da <b>SGP - Soluções em Gestão Pública</b>, entregar e melhorar seus produtos ou serviços. 📓 Interesse legítimo.</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Compreender e avaliar os interesses, desejos e necessidades dos titulares dos dados para atualização de websites, bem como o desenvolvimento de novos produtos e serviços. 📓 Interesse legítimo.</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Atender as demandas originárias do sistema de atendimento ao cliente. 📓 Interesse legítimo, Consentimento.</li>                            
                        </ul>
                    </div>
                </div>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <ul>
                            <li className={styles.coloredTitleSpecial}>1. Clientes - <em>Dados Pessoais Sensíveis</em></li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/> Finalidade e 📓 Base Legal</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Para que a <b>SGP - Soluções em Gestão Pública</b> possa complementar a análise físico-química do produto quando identificado algum tipo de desvio. 📓 Proteção da vida ou da incolumidade física do titular ou de Terceiro; e Cumprimento de obrigação legal e regulatória.</li>                        
                        </ul>
                    </div>
                </div>
                <hr />
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3 style={{marginBlock: "20px"}}>IV. Finalidades do processamento de dados e base legal</h3>
                        <ul>
                            <li>O tratamento dos dados pessoais será realizado de acordo com as leis de proteção de dados aplicáveis, apenas para fins limitados, explícitos e legítimos e com as disposições estabelecidas neste Termo de Privacidade.</li>
                            <li>Os dados pessoais serão tratados pelas razões e bases legais descritas abaixo, a fim de cumprir com as obrigações assumidas pela <b>SGP - Soluções em Gestão Pública</b>, resultantes da legislação aplicável e obrigações legais.</li>
                            <li className={styles.coloredTitleSpecial}>2. Fornecedores e Parceiros de Negócios - <em>Dados Pessoais</em></li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Finalidade e 📓 Base Legal</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Analisar o cadastro do indivíduo perante órgãos federais e estaduais, e outras autoridades competentes. 📓 Cumprimento de obrigação legal e regulatória, Interesse legítimo.</li>
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Gerenciar relacionamentos comerciais, atendimento de pedidos, pagamento e faturamento de bens e serviços, contatando o Fornecedor ou Parceiro de Negócio. 📓 Obrigação contratual, Interesse Legítimo.</li> 
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Realizar operações promocionais, marketing direto para promover a posição da <b>SGP - Soluções em Gestão Pública</b> no mercado. 📓 Interesse legítimo, Consentimento.</li> 
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Detectar e prevenir fraude para garantir a segurança e integridade da <b>SGP - Soluções em Gestão Pública</b>. 📓 Interesse legítimo.</li> 
                            <li className={styles.withIcon}><AiOutlineCheckCircle/> Garantir a segurança e integridade da <b>SGP - Soluções em Gestão Pública</b> e dos indivíduos. 📓 Para a proteção da vida ou incolumidade física do titular ou de Terceiro.</li> 
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Responder os procedimentos legais ou de órgãos administrativos/entidades reguladoras. Cumprir as obrigações legais e / ou investigações regulatórias, auxiliando a <b>SGP - Soluções em Gestão Pública</b> no contexto de qualquer litígio ou arbitragem e protegendo a <b>SGP - Soluções em Gestão Pública</b> contra lesões, roubo, responsabilidade legal, fraude, abuso ou outra conduta imprópria. 📓 Cumprimento de obrigação legal, Exercício regular de direitos, Interesse legítimo.</li> 
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Gerenciar transações da <b>SGP - Soluções em Gestão Pública</b> (por exemplo, fusão ou aquisição) para conduzir negociações comerciais da <b>SGP - Soluções em Gestão Pública</b>. 📓 Cumprimento de obrigação legal e regulatória, Cumprimento de obrigação contratual, Interesse legítimo.</li> 
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Gerenciar as operações da <b>SGP - Soluções em Gestão Pública</b>, incluindo a operação e monitoramento do bom funcionamento e segurança dos sistemas de TI da <b>SGP - Soluções em Gestão Pública</b> para garantir sua proteção e segurança. 📓 Interesse legítimo.</li> 
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Gerenciar incidentes de saúde e segurança. 📓 Para a proteção da vida ou incolumidade física do titular ou de Terceiro.</li> 
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Gerenciar entregas e remessas de produtos para administrar os negócios da <b>SGP - Soluções em Gestão Pública</b>, entregar e melhorar seus produtos ou serviços. 📓 Cumprimento de obrigação contratual, Interesse legítimo.</li> 
                            <li className={styles.withIcon}><AiOutlineCheckCircle/>Compreender e avaliar os interesses, desejos e necessidades dos titulares dos dados para atualização de websites, bem como o desenvolvimento de novos produtos e serviços. 📓 Interesse legítimo.</li> 
                        </ul>
                        <p style={{marginBlock: "20px"}}>A <b>SGP - Soluções em Gestão Pública</b> garante que os procedimentos de governança interna especifiquem claramente os motivos de tratamento de dados pessoais. Antes de usar seus dados pessoais para uma finalidade diferente daquela para a qual foram inicialmente coletados, você será informado sobre essa nova finalidade.</p>
                    </div>
                </div>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>V. Compartilhamento de Dados</h3>
                        <ul >
                            <li>Em conexão com as atividades descritas na Seção IV, a SGP - Soluções em Gestão Pública pode precisar, de tempos em tempos, divulgar ou disponibilizar dados pessoais a prestadores de serviços terceirizados relevantes (por exemplo, prestadores de serviços de gestão de relacionamento com clientes / fornecedores, consultores profissionais), parceiros de negócios da SGP - Soluções em Gestão Pública, autoridades regulatórias, órgãos governamentais e compradores potenciais da SGP - Soluções em Gestão Pública ou de um negócio da SGP - Soluções em Gestão Pública.</li>
                            <li>A SGP - Soluções em Gestão Pública somente concederá acesso aos dados pessoais quando necessário e esse acesso será limitado aos dados pessoais necessários para a finalidade para a qual o acesso foi concedido.</li>
                            <li>A autorização para acessar dados pessoais estará sempre vinculada à finalidade, de forma que nenhuma autorização será estendida para acessar dados pessoais em caráter pessoal. Os prestadores de serviços somente receberão dados pessoais de acordo com os fins do contrato de serviço com a SGP - Soluções em Gestão Pública.</li>
                        </ul>
                    </div>
                </div>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>VI. Retenção de Dados Pessoais</h3>
                        <ul>
                            <li>A SGP - Soluções em Gestão Pública não reterá os dados pessoais dos titulares por mais tempo do que o necessário para os fins a que foram coletados ou de outra forma tratados, conforme estabelecido neste Termo e para os quais a SGP - Soluções em Gestão Pública tenha uma base legal válida. Em qualquer caso, não o reteremos por mais tempo do que o permitido pelos períodos de retenção legais locais.</li>
                            <li>No caso de a SGP - Soluções em Gestão Pública estar envolvida em quaisquer reivindicações legais, temos o direito de continuar a processar seus dados pessoais que sejam relevantes para tais reivindicações, sujeito aos requisitos de retenção locais aplicáveis.</li>
                        </ul>
                    </div>
                </div>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>VII. Direitos dos Titulares dos Dados</h3>
                        <ul>
                            <li>Os titulares dos dados possuem os seguintes direitos:</li>
                            <li><b>1.</b> Confirmar a existência do tratamento dos dados;</li>
                            <li><b>2.</b> Acessar os dados compartilhados;</li>
                            <li><b>3.</b> Corrigir dados incompletos, imprecisos ou desatualizados;</li>
                            <li><b>4.</b> Bloquear, eliminar ou anonimizar os dados desnecessários, excessivos ou tratados em desconformidade com a LGPD;</li>
                            <li><b>5.</b> Realizar a portabilidade dos dados para outro fornecedor de serviços ou produtos, mediante requisição expressa, de acordo com a regulamentação da Autoridade Nacional, observados os segredos comercial e industrial;</li>
                            <li><b>6.</b> Eliminar os dados pessoais processados com o consentimento do Titular dos Dados, ressalvadas as hipóteses de guarda para cumprimento de obrigação legal ou regulatória;</li>
                            <li><b>7.</b> Informar a respeito do uso compartilhado de dados pessoais com as entidades públicas e privadas com as quais a SGP - Soluções em Gestão Pública compartilhou dados;</li>
                            <li><b>8.</b> Informar sobre a possibilidade de não fornecer consentimento e sobre as consequências da negativa;</li>
                            <li><b>9.</b> Possibilidade de revogar o consentimento, por meio de um procedimento gratuito e facilitado;</li>
                            <li><b>10.</b> Realizar a oposição ao processamento se houver descumprimento das disposições da LGPD;</li>
                        </ul>
                    </div>
                </div>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>VIII. Contato do Encarregado da Proteção de Dados Pessoais - DPO</h3>
                        <ul>
                            <li>Monitorar e garantir a conformidade do tratamento de dados pessoais na SGP - Soluções em Gestão Pública com este Termo e as leis de proteção de dados aplicáveis é responsabilidade do DPO.</li>
                            <li>Conforme mencionado acima, o titular dos dados pode entrar em contato com o DPO para questões relacionadas ao tratamento de seus dados pessoais e para exercer seus direitos conforme mencionado no item VII.</li>
                        </ul>
                    </div>
                </div>
                <div className={styles.topico}>
                    <div className={styles.parteN}>
                        <h3>IX. Diversos</h3>
                        <ul>
                            <li>A SGP - Soluções em Gestão Pública reserva-se o direito de fazer alterações ou atualizações neste Termo de Privacidade, a qualquer critério e a qualquer momento.</li>
                        </ul>
                    </div>
                </div>
                <hr />
                <div className={styles.segurancaDados}>
                    <p>ANPD - Autoridade Nacional de Proteção de Dados.</p>
                    <p>DPO - Data Protection Officer - Encarregado da Proteção de Dados.</p>
                    <p>LGPD - Lei Geral de Proteção de Dados.</p>
                </div>
                <p className={styles.revisao}>Este Termo de Consentimento da Privacidade foi revisado em 15 de Dezembro de 2021.</p>
                
            </div>
        </div>
        <FooterCompleto />
    </div>
  );
}
