import Head from "next/head";
import React from "react";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Assessoria.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";
import Button from "@/components/Button";
import Image from "next/image";
import { useRouter } from "next/router";

export default function SolucoesInovadoras() {
    const { push } = useRouter();

    return (
        <div className={styles.main}>
        <Head>
            <title>SGP - Soluções em Gestão Público</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="shortcut icon" href="/favicon/favicon.ico" />
        </Head>
        <Navbar />
        <section className={styles.content}>
            <div className={styles.bluredBall}></div>
            <div className={styles.headerContent}>
            <div className={styles.left}>
                <div className={styles.mainTitle}>
                <h1> Assessoria <em>{"On-Line"}</em> Hora Certa </h1>
                <hr />
                </div>
                <Button color="orange" title="Saber mais" />
            </div>
            <div className={styles.center}>
                <p>Assessoramento exclusivo, prático e dinâmico, que viabilizará o esclarecimento de todas as suas dúvidas por blocos temáticos, em tempo real, com hora marcada, em atendimento ao vivo por uma equipe altamente qualificada. </p>
            </div>
            <div className={styles.right}>
                <Image
                alt="Fly falando sobre Assessoria On-line Hora Certa"
                src="/images/solucoes-inovadoras/assessoria/header.webp"
                width={453}
                height={323}
                className={"imgOnHover"}
                />
            </div>
            </div>
        </section>
        <div className={styles.pageSize}>
            <div className={styles.contentAll}>
                <div className={styles.areasAtuacao}>
                    <div>
                        <h1>Áreas de atuação em blocos temáticos:</h1>
                        <hr />
                        <ul>
                            <li><b>BLOCO 01: </b><span>Licitações, Contratações Diretas e Contratos Administrativos.</span></li>
                            <li><b>BLOCO 02: </b><span>Agentes Públicos, Prefeitos e Vereadores, Processo Administrativo Disciplinar e Sindicância, Direito Eleitoral (afeto aos Poderes Legislativo e Executivo), Análise de projetos de lei quanto à iniciativa e à competência.</span></li>
                            <li><b>BLOCO 03: </b><span>Contabilidade e Contabilidade Pública, Organização Contábil, Gestão, Controle Financeiro, Encerramento do Exercício, Prestação de Contas, Audesp, Lei de Diretrizes Orçamentárias e Escrituração Fiscal Digital de Retenções e Outras Informações Fiscais (EFD-Reinf).</span></li>
                            <li><b>BLOCO 04: </b><span>eSocial, Recursos Humanos, Departamento Pessoal e DCTFWEB.</span></li>
                            <li><b>BLOCO 05: </b><span>Direito Tributário em geral, tributos municipais, estaduais e federais, retenções na fonte, gestão de créditos tributários, dentre outros.</span></li>
                            <li><b>BLOCO 06: </b><span>Outros temas mediante prévia consulta.</span></li>
                        </ul>
                    </div>
                    <div>
                        <p>Contratação mínima de 1 hora de esclarecimento de dúvidas por bloco temático, marcando-se previamente dia e horário para atendimento on-line, dentro da disponibilidade do contratante e dos nossos consultores. </p>
                        <p>No dia e horário marcados, consultor e cliente entrarão na plataforma on-line, por meio de link de acesso previamente encaminhado pela SGP, para o atendimento pré-agendado de no mínimo 1 hora.</p>
                        <p>Durante o período de atendimento on-line, todas as suas dúvidas poderão ser esclarecidas por quem realmente entende de cada assunto.</p>
                        <b className={styles.bold}>Rápido, fácil e com muita segurança técnica!</b>
                        <Button color="orange" title="Solicite um orçamento"/>
                    </div>
                </div>
                <div className={styles.img}></div>
                <div className={styles.professores}>
                    <h1>Corpo docente</h1>
                    <p>
                        Conheça nosso corpo docente de excelência e gabarito, que aplicam e
                        vivenciam as melhores boas práticas do mercado.
                    </p>
                    <Button
                        onClick={() => push("/nossos-professores")}
                        color="darkBlue"
                        title="Ver todos os professores"
                    />
                </div>
            </div>
        </div>
        <FooterCompleto />
        </div>
    );
}
