import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import styles from "@/styles/SolucoesInovadoras.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";
import { useRouter } from "next/router";
import Button from "@/components/Button";
import { CursosTreinamentosType } from "@/typings/CursosTreinamentos";
import { InfoOrientacoes } from "@/utils/orientacoes";
import { TiposOrientacoes } from "@/utils/tipos-orientacoes";
import { AiOutlineCheckCircle } from "react-icons/ai";
import Image from "next/image";

export default function SolucoesInovadoras() {
  const { push } = useRouter();
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [modalContent, setModalContent] = useState<CursosTreinamentosType>();

  function modalState(content: CursosTreinamentosType) {
    setIsModalOpen(!isModalOpen);
    setModalContent(content)
  }

  return (
    <div className={styles.main}>
      <Head>
        <title>SGP - Soluções em Gestão Público</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section className={styles.content}>
        <div className={styles.bluredBall}></div>
        <div className={styles.headerContent}>
          <h1>Orientações SGP</h1>
          <hr />
          <p>
          A Orientação SGP ampliou sua área de atuação. Agora são três Consultorias pelo preço de uma.
          </p>

          <div className={styles.buttonFrase}>
            <b>Tradicional, tributário e RH | DP | eSocial</b>
            <Button color="blue" title="Saber Mais!" />

          </div>
        </div>
      </section>
      <section className={styles.pageSize}>
        {/* <ProfessoresComponent /> */}
        <div className={styles.orientacoes}>
          {InfoOrientacoes.map(({descricao, tipo, title, img}) => (
            <div key={descricao} style={{backgroundImage: `url(${img})`}} className={styles.orientacao}>
              <div className={styles.headerTipos}>
                {tipo.map((x, index) => (
                    <span key={index}>{x}</span>
                  )
                )}
              </div>
              <div className={styles.descricao}>
                <h2>{title}</h2>
                <p>{descricao}</p>
              </div>
            </div>
          ))}
        </div>
      </section>
      <section className={styles.image}></section>
      <section className={styles.topicosOrientacoes}>
        <div className={styles.header}>
          <h1>Orientação SGP Tradicional</h1>
          <p>Atuante na área do Direito Administrativo e Direito Municipal.</p>
          <hr />
        </div>
        <div className={styles.fullLista}>
          {TiposOrientacoes.map((x, i) => (
            <ul className={styles.topicosLista}>
              <li className={styles.listaInterna}>
                {x.map((x) => (

                  <p><AiOutlineCheckCircle />{x}</p>
                ))}  
              </li>
            </ul>
          ))}
        </div>
      </section>
      <section className={styles.orientacoesTributarias}>
        <div className={styles.orientacaoSGPTributaria}>
            <div className={styles.textos}>
              <hr />
              <h1>Orientação SGP Tributária</h1>
              <p>Atuante na área do Direito Tributário em geral (inclusive impostos, taxas e contribuições, nos âmbitos municipal, estadual e federal.</p>
              <Button color="darkBlue" title="Envie sua solicitação"/>
            </div>
          <div className={styles.img}>
            <Image src="/images/solucoes-inovadoras/tres-maos.webp" width={593} height={385} alt="Três mãos. Uma delas digitando em um notebook cinza, outra escrevendo em uma prancheta e a última está escrevendo e digitando" />
          </div>
        </div>
        <div className={styles.orientacaoSGPTributaria}>
          <div className={styles.img}>
            <Image src="/images/solucoes-inovadoras/pessoas-discutindo.webp" width={592} height={384} alt="Três mãos. Uma delas digitando em um notebook cinza, outra escrevendo em uma prancheta e a última está escrevendo e digitando" />
          </div>
          <div className={styles.textos}>
            <hr />
            <h1>Orientação SGP RH | DP | eSocial</h1>
            <p>Atuante nas áreas de Recursos Humanos, Departamento Pessoal e eSocial.</p>
            <Button color="darkBlue" title="Envie sua solicitação"/>
          </div>
        </div>
      </section>

      <section className={styles.assesoriaJuridicaInLoco}>
        <div className={styles.texto}>
          <hr />
          <h1>Assessoria Jurídica <em>In Loco</em></h1>
          <p>Fazemos visitações no órgão ou entidade, a fim de realizar um assessoramento pessoal e diferenciado, exclusivamente na área de licitações e contratos.</p>
          <p>Num atendimento totalmente personalizado e exclusivo, nosso Corpo Jurídico, com toda sua expertise, poderá fazer quantas visitações forem necessárias para atender às suas necessidades administrativas.</p>
        </div>
      </section>

      <section className={styles.informacoesAssesoriaMentoria}>
        <div className={styles.assesoriaLicitacoes}>
            <div className={styles.textos}>
              <hr />
              <h1>Assessoria em Licitações Públicas para Empresas Privadas</h1>
              <p>A qualidade dos nossos serviços, reconhecida pelos órgãos públicos em todo Brasil, agora à disposição das empresas privadas.</p>
              <p>Se você quer vender seus produtos e serviços para o governo, mas não sabe como, a SGP vai lhe assessorar, desde o cadastramento até a participação na licitação ou processo de contratação direta.</p>
              <Button color="darkBlue" title="Entre em contato"/>
            </div>
          <div className={styles.img}>
            <Image src="/images/solucoes-inovadoras/homem-no-telefone.webp" width={432} height={451} alt="Três mãos. Uma delas digitando em um notebook cinza, outra escrevendo em uma prancheta e a última está escrevendo e digitando" />
          </div>
        </div>
        <div className={styles.mentoriaNovaLei}>
          <div className={styles.img}>
            <Image src="/images/solucoes-inovadoras/mao-escrevendo.webp" width={355} height={401} alt="Três mãos. Uma delas digitando em um notebook cinza, outra escrevendo em uma prancheta e a última está escrevendo e digitando" />
            <b>Mentoria</b>
            <div className={styles.informacoes}>
              <span>12 Encontros</span>
              <span>36 Horas</span>
              <span>Com certificado!</span>
            </div>
          </div>
          <div className={styles.textos}>
            <hr />
            <h1>Mentoria da Nova Lei de Licitações e Contratos Administrativos - Lei nº 14.133/2021</h1>
            <p>A SGP, pensando em novas soluções para o dia a dia dos nossos clientes, envolvidos na área de licitações e contratos, tanto do setor público como da iniciativa privada, acaba de lançar sua mais nova Solução técnica.</p>
            <p>Nossa Mentoria consiste em 12 encontros semanais on-line, totalizando uma carga horária de 36 horas, com expedição de Certificado para os participantes.</p>
            <p>Serão painéis on-line, com professores renomados do Direito Público, palestras de duas horas de duração e mais uma hora para esclarecimento de dúvidas ao vivo sobre o tema abordado.</p>
            <Button color="darkBlue" title="Entre em contato"/>
          </div>
        </div>
      </section>                    
      <section className={styles.mbaLicitacoesContratacoesADM}>
        <h1>MBA em Licitações e Contratações da Administração Pública</h1>
        <hr />
        <div className={styles.objetivosHorarios}>
          <div>
            <h3>Objetivo Geral do curso</h3>
            <p>O curso de MBA em Licitações e Contratações da Administração Pública tem o objetivo de propiciar uma visão moderna, atual, prática e dinâmica das Licitações e Contratações Públicas em geral, sob todas as suas formas, oferecendo subsídios teóricos e práticos, incentivando a pesquisa científica e preparando os profissionais no fomento de práticas inovadoras no âmbito jurídico e profissional.</p>
          </div>
          <div>
            <h3>Objetivo Geral do curso</h3>
            <ul>
              <li>
                <AiOutlineCheckCircle/>
                <span>Capacitar profissionais para atuação nas demandas de Licitações Públicas e Contratos da Administração Pública;</span>
              </li>
              <li>
                <AiOutlineCheckCircle/>
                <span>Qualificar profissionais para a prática dos processos de contratação, desde a fase interna até a execução contratual;</span>
              </li>
              <li>
                <AiOutlineCheckCircle/>
                <span>Estimular a produção acadêmica e o debate crítico sobre as questões interdisciplinares, envolvendo a área do Direito e suas interfaces;</span>
              </li>
              <li>
                <AiOutlineCheckCircle/>
                <span>Desenvolver competências para a pesquisa e para a produção de conhecimento em Licitações Públicas e Contratos da Administração Pública.</span>
              </li>
            </ul>
          </div>
          <div>
            <h3>Objetivo Geral do curso</h3>
            <ul>
              <li>
                <AiOutlineCheckCircle/>
                <span>As aulas serão online e ministradas às sextas-feiras, no período noturno (19h - 23h00min) e aos sábados, no período matutino (8h30 - 12h30) e vespertino (13h30 - 17h30), conforme a carga horária da disciplina.</span>
              </li>
              <li>
                <AiOutlineCheckCircle/>
                <span>As aulas serão ofertadas preferencialmente duas vezes por semana.</span>
              </li>
              <li>
                <AiOutlineCheckCircle/>
                <span>Carga Horária: 360h</span>
              </li>
              <li>
                <AiOutlineCheckCircle/>
                <span>Inscrições abertas no período programado</span>
              </li>
              <li>
                <Button color="darkBlue" title="Quero fazer minha inscrição!"/>
              </li>
            </ul>
          </div>
          <div className={styles.img}>
            <Image src="/images/solucoes-inovadoras/pessoas-prestando-atencao.webp" width={387} height={301} alt="Três mãos. Uma delas digitando em um notebook cinza, outra escrevendo em uma prancheta e a última está escrevendo e digitando" />
            <b>MBA</b>
            <div className={styles.informacoes}>
              <span>12 Encontros</span>
              <span>36 Horas</span>
              <span>Com certificado!</span>
            </div>
          </div>
        </div>
      </section>
      <section className={styles.indicacoes}>
        <div className={styles.contentIndicacoes}>
          <hr />
          <h1>Porque somos a empresa mais indicada em cursos e treinamentos?</h1>
          <div className={styles.listaExplicativa}>
            <ul>
              <li>Profissionais altamente qualificados</li>
              <li>Conteúdo programático completo</li>
              <li>Temas relevantes e atuais</li>
              <li>Saneamento de todas as dúvidas</li>
              <li>Aulas expositivas</li>
              <li>Dinâmicas em grupo</li>
              <li>Alto índice de satisfação</li>
            </ul>
            <ul>
              <li>Conhecimento prático e técnico</li>
              <li>Material didático de qualidade</li>
              <li>Adaptações às necessidades específicas</li>
              <li>Metodologia diferenciada</li>
              <li>Estudos de casos práticos</li>
              <li>Carga horária adequada</li>
              <li>Reconhecimento no mercado</li>
            </ul>
          </div>
        </div>
      
      
      </section>

      <FooterCompleto />
      

    </div>
  );
}