import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Mba.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";
import { useRouter } from "next/router";
import Button from "@/components/Button";
import { CursosTreinamentosType } from "@/typings/CursosTreinamentos";
import Image from "next/image";

export default function SolucoesInovadoras() {
  const { push } = useRouter();
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [modalContent, setModalContent] = useState<CursosTreinamentosType>();

  function modalState(content: CursosTreinamentosType) {
    setIsModalOpen(!isModalOpen);
    setModalContent(content);
  }

  return (
    <div className={styles.main}>
      <Head>
        <title>SGP - Soluções em Gestão Público</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section className={styles.content}>
        <div className={styles.bluredBall}></div>
        <div className={styles.headerContent}>
          <div className={styles.left}>
            <div className={styles.mainTitle}>
              <h1> MBA em Licitações </h1>
              <hr />
            </div>
            <p>
              Você sabia que conhecimento é o único bem que ninguém pode tirar
              de você?
            </p>
            <b>MBA em Licitações e Contratações da Administração Pública.</b>
            <p>
              Na SGP - Soluções em Gestão Pública há um time de professores
              altamente qualificados !!!
            </p>
          </div>
          <div className={styles.center}>
            <div>
              <b>Faça agora sua inscrição!</b>
              <p>Com parcelas que cabem no seu bolso</p>
            </div>
            <div>
              <h3>
                Até 10 parcelas <br /> Matrícula R$ 680,00{" "}
                <b> + 9 parcelas de R$ 680,00 </b>
              </h3>
              <span>(somente no cartão de crédito ou boleto bancário)</span>
            </div>
            <div>
              <p>
                {" "}
                ou <b>5% </b>de desconto <b>à vista</b>
              </p>
              <span>(PIX, Depósito, TED, Cartão de Débito)</span>
            </div>
          </div>
          <div className={styles.right}>
            <Image
              alt="Fly falando sobre o MBA Online em licitações e contratações da administração Pública"
              src="/images/solucoes-inovadoras/mba/mba.webp"
              width={453}
              height={323}
            />
            <div className={styles.title}>
              <h1> MBA em Licitações </h1>
              <hr />
            </div>
          </div>
        </div>
      </section>
      <div className={styles.pageSize}>
        <section className={styles.professores}>
          <h1>Corpo docente</h1>
          <p>
            Conheça nosso corpo docente de excelência e gabarito, que aplicam e
            vivenciam as melhores boas práticas do mercado.
          </p>
          <Button
            onClick={() => push("../nossos-professores")}
            color="darkBlue"
            title="Ver todos os professores"
          />
        </section>
        <section className={styles.mbaLicitacoesContratacoesAdmPublica}>
          <h1>MBA em Licitações e Contratações da Administração Pública</h1>
          <hr />
          <div>
            <div className={styles.objGeralCurso}></div>
            <div className={styles.objEspecificoCurso}></div>
            <div className={styles.horarioELocal}></div>
            <div className={styles.imagem}></div>
          </div>
        </section>
      </div>
      <FooterCompleto />
    </div>
  );
}
