import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Mba.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";
import { useRouter } from "next/router";
import Button from "@/components/Button";
import { CursosTreinamentosType } from "@/typings/CursosTreinamentos";
import Image from "next/image";
import { AiOutlineCheckCircle } from "react-icons/ai";

export default function SolucoesInovadoras() {
  const { push } = useRouter();
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [modalContent, setModalContent] = useState<CursosTreinamentosType>();

  function modalState(content: CursosTreinamentosType) {
    setIsModalOpen(!isModalOpen);
    setModalContent(content);
  }

  return (
    <div className={styles.main}>
      <Head>
        <title>SGP - Soluções em Gestão Público</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section className={styles.content}>
        <div className={styles.bluredBall}></div>
        <div className={styles.headerContent}>
          <div className={styles.left}>
            <div className={styles.mainTitle}>
              <h1> MBA em Licitações </h1>
              <hr />
            </div>
            <p>
              Você sabia que conhecimento é o único bem que ninguém pode tirar
              de você?
            </p>
            <b>MBA em Licitações e Contratações da Administração Pública.</b>
            <p>
              Na SGP - Soluções em Gestão Pública há um time de professores
              altamente qualificados !!!
            </p>
          </div>
          <div className={styles.center}>
            <div>
              <b>Faça agora sua inscrição!</b>
              <p>Com parcelas que cabem no seu bolso</p>
            </div>
            <div>
              <h3>
                Até 10 parcelas <br /> Matrícula R$ 680,00{" "}
                <b> + 9 parcelas de R$ 680,00 </b>
              </h3>
              <span>(somente no cartão de crédito ou boleto bancário)</span>
            </div>
            <div>
              <p>
                {" "}
                ou <b>5% </b>de desconto <b>à vista</b>
              </p>
              <span>(PIX, Depósito, TED, Cartão de Débito)</span>
            </div>
          </div>
          <div className={styles.right}>
            <Image
              alt="Fly falando sobre o MBA Online em licitações e contratações da administração Pública"
              src="/images/solucoes-inovadoras/mba/mba.webp"
              width={453}
              height={323}
            />
            <div className={styles.title}>
              <h1> MBA em Licitações </h1>
              <hr />
            </div>
          </div>
        </div>
      </section>
      <div className={styles.pageSize}>
        <section className={styles.professores}>
          <h1>Corpo docente</h1>
          <p>
            Conheça nosso corpo docente de excelência e gabarito, que aplicam e
            vivenciam as melhores boas práticas do mercado.
          </p>
          <Button
            onClick={() => push("../nossos-professores")}
            color="darkBlue"
            title="Ver todos os professores"
          />
        </section>
        <section className={styles.mbaLicitacoesContratacoesAdmPublica}>
          <h1>MBA em Licitações e Contratações da Administração Pública</h1>
          <hr />
          <div className={styles.infosCurso}>
            <div className={styles.objGeralCurso}>
              <h2>Objetivo Geral do curso</h2>
              <p> O curso de MBA On-Line em Licitações e Contratações da Administração Pública tem o objetivo de propiciar uma visão moderna, atual, prática e dinâmica das Licitações e Contratações Públicas em geral, sob todas as suas formas, oferecendo subsídios teóricos e práticos, incentivando a pesquisa científica e preparando os profissionais no fomento de práticas inovadoras no âmbito jurídico e profissional.</p>
            </div>
            <div className={styles.objEspecificoCurso}>
              <h2>Objetivo específicos do curso </h2>
              <ul>
                <li> 
                  <AiOutlineCheckCircle />  
                  <span>Capacitar profissionais para atuação nas demandas de Licitações Públicas e Contratos da Administração Pública;</span>
                </li>
                <li> 
                  <AiOutlineCheckCircle /> 
                  <span>Qualificar profissionais para a prática dos processos de contratação, desde a fase interna até a execução contratual;</span>
                </li>
                <li> 
                  <AiOutlineCheckCircle />
                  <span>Estimular a produção acadêmica e o debate crítico sobre as questões interdisciplinares, envolvendo a área do Direito e suas interfaces;</span>
                </li>
                <li> 
                  <AiOutlineCheckCircle /> 
                  <span>Desenvolver competências para a pesquisa e para a produção de conhecimento em Licitações Públicas e Contratos da Administração Pública.</span>
                </li>
              </ul>
            </div>
            <div className={styles.horarioELocal}>
              <h2>Conheça os dias, horários e local do curso</h2>
              <ul>
                <li> 
                  <AiOutlineCheckCircle />  
                  <span>As aulas serão on-line e ministradas às sextas-feiras, no período noturno (das 19h às 23h), e aos sábados, nos períodos matutino (das 8h30 às 12h30) e vespertino (das 13h30 às 17h30), conforme a carga horária da disciplina.</span>
                </li>
                <li> 
                  <AiOutlineCheckCircle /> 
                  <span>As aulas serão ofertadas preferencialmente duas vezes por semana.</span>
                </li>
                <li> 
                  <AiOutlineCheckCircle />
                  <span>Carga Horária: 360 horas.</span>
                </li>
                <li> 
                  <AiOutlineCheckCircle /> 
                  <span>Inscrições abertas no período programado.</span>
                </li>
                <li>
                  <Button color="darkBlue" title="Quero fazer minha inscrição!"/>
                </li>
              </ul>
            </div>
            <div className={styles.imgSpace}>
              <div className={styles.img}>
                <Image src="/images/solucoes-inovadoras/pessoas-prestando-atencao.webp" width={387} height={301} alt="Três mãos. Uma delas digitando em um notebook cinza, outra escrevendo em uma prancheta e a última está escrevendo e digitando" />
                <b>MBA</b>
                <div className={styles.informacoes}>
                  <span>12 Encontros</span>
                  <span>36 Horas</span>
                  <span>Com certificado!</span>
                </div>
              </div>
            </div>
            
          </div>
        </section>
      </div>
      <FooterCompleto />
    </div>
  );
}
