import Head from "next/head";
import React from "react";
import Navbar from "@/components/Navbar";
import styles from "@/styles/ProjetoSGP.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";
import Button from "@/components/Button";
import Image from "next/image";
import { useRouter } from "next/router";

export default function SolucoesInovadoras() {
    const { push } = useRouter();

    return (
        <div className={styles.main}>
        <Head>
            <title>SGP - Soluções em Gestão Público</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="shortcut icon" href="/favicon/favicon.ico" />
        </Head>
        <Navbar />
        <section className={styles.content}>
            <div className={styles.bluredBall}></div>
            <div className={styles.headerContent}>
            <div className={styles.left}>
                <div className={styles.mainTitle}>
                    <hr />
                    <h1> Projeto SGP de Regulamentação e/ou Revisão Legislativa </h1>
                    </div>
                    <Button color="blue" title="Saber mais" />
                </div>
            <div className={styles.center}>
                <p>A fim de aproveitar ainda mais adequadmente sua equipe altamente qualificada, a SGP apresenta ao mercado sua mais nova Solução Inovadora: a elaboração de minutas de regulamentos da nova Lei de Licitações e Contratos (Lei nº 14.133/2021), bem como a elaboração de minutas de Regimentos Internos, Leis Orgânicas Municipais, Estatutos de Servidores Públicos Municipais e Reestruturação de Cargos e Salários dos Servidores Municipais.</p>
            </div>
            <div className={styles.right}>
                <Image
                    alt="Fly falando sobre Assessoria On-line Hora Certa"
                    src="/images/solucoes-inovadoras/projeto/martelo.webp"
                    width={453}
                    height={323}
                />
            </div>
            </div>
        </section>
        <div className={styles.pageSize}>
            <div className={styles.contentAll}>
                <div className={styles.infoProduto}>
                    <h1>Áreas de atuação em blocos temáticos:</h1>
                    <hr />

                    <p>Em face da necessidade de regulamentação de diversos dispositivos da nova Lei de Licitações e Contratos (Lei nº 14.133/2021), a SGP oferece a seus clientes, por meio do seu corpo técnico-jurídico altamente qualificado, a prestação dos serviços de elaboração de minutas de regulamentos da nova Lei, de forma parcial ou integral, segundo as necessidades específicas do órgão ou entidade contratante.</p>
                    <p>Há aproximadamente 40 artigos da nova Lei de Licitações e Contratos que precisam ser regulamentados. </p>
                    <p>Estados e Municípios têm duas alternaivas: (i) ou aguardar a Administração Federal regulamentar os respectivos artigos e valerem-se dos regulamentos federais, com fundamento no art. 187 da Lei 14.133/2021, (ii) ou regulamentarem diretamente em seu âmbito os dispositivos de seu interesse.</p>
                    <p> Dessa maneira, a fim de auxiliarmos nossos clientes nesta árdua empreitada, criamos mais esta nova Solução técnica, que viabilizará a implementação total ou parcial da nova Lei de Licitações, nos âmbitos municipal e estadual.</p>

                </div>
                <div className={styles.areasAtuacao}>
                    <div>
                        <h1>Confira os 8 principais regulamentos que têm sido mais procurados nos âmbitos municipal e estadual:</h1>
                        <hr />
                        <ul>
                            <li>1- Contratações Diretas</li>
                            <li>2 - Procedimentos do pregão presencial e eletrônico</li>
                            <li>3 - Habilitação</li>
                            <li>4- Credenciamento</li>
                            <li>5 - Pré-Qualificação</li>
                            <li>6 - PMI</li>
                            <li>7 - SRP</li>
                            <li>8 - Registro Cadastral</li>
                        </ul>
                        <p>Além da implementação da nova Lei de Licitações e Contratos (Lei nº 14.133/2021), a SGP também está apta a elaborar e/ou reviar com toda segurança jurídica minutas de Regimentos Internos, Leis Orgânicas Municipais, Estatutos de Servidores Públicos Municipais e Reestruturação de Cargos e Salários dos Servidores Municipais.</p>
                        <Button color="blue" title="Solicite um orçamento"/>
                    </div>
                    <div className={styles.imageLei}>
                        <Image src={"/images/solucoes-inovadoras/projeto/lei.webp"} alt="Lei" width={592} height={583} />
                    </div>
                </div>
                <div className={styles.img}></div>
                <div className={styles.professores}>
                    <h1>Corpo docente</h1>
                    <p>
                        Conheça nosso corpo docente de excelência e gabarito, que aplicam e
                        vivenciam as melhores boas práticas do mercado.
                    </p>
                    <Button
                        onClick={() => push("/nossos-professores")}
                        color="darkBlue"
                        title="Ver todos os professores"
                    />
                </div>
            </div>
        </div>
        <FooterCompleto />
        </div>
    );
}
