import Head from "next/head";
import React from "react";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Galeria.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";

export default function Galeria() {
  return (
    <div className={styles.main}>
      <Head>
        <title>SGP - Soluções em Gestão Público</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.content}>
        <div className={styles.bluredBall}></div>
        <div className={styles.headerContent}>
          <h1>Canal SGP</h1>
          <hr />
        </div>
      </div>
      <div className={styles.pageSize}></div>
      <FooterCompleto />
    </div>
  );
}
