import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Galeria.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";
import { useRouter } from "next/router";
import { CursosTreinamentosType } from "@/typings/CursosTreinamentos";


export default function NossosPeriodicos() {
    const { push } = useRouter();
    const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
    const [modalContent, setModalContent] = useState<CursosTreinamentosType>();

    return (
        <div className={styles.main}>
            <Head>
                <title>SGP - Soluções em Gestão Público</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <div className={styles.content}>
                <div className={styles.bluredBall}></div>
                <div className={styles.headerContent}>
                <h1>Galeria de fotos SGP</h1>
                <hr />
                <p> Confira os melhores momentos que registramos durante nossos cursos e treinamentos. </p>
                </div>
            </div>
            <FooterCompleto />
        </div>
    );
}
