import React from "react";
import styles from "../styles/PubliqueConosco.module.scss";
import Image from "next/image";
import Button from "@/components/Button";
import { useRouter } from "next/router";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import { FooterCompleto } from "@/components/FooterCompleto";

export default function PubliqueConosco() {
  const { push } = useRouter();

  return (
    <main className={styles.main}>
      <Head>
        <title>SGP - Soluções em Gestão Público</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
      </Head>
      <Navbar />

      <div className={styles.pageSize}>
        <section className={styles.degustacaoAll}>
          <div className={styles.degustacao}>
            <div className={styles.leftSide}>
              <h1>Publique conosco seu artigo ou parecer.</h1>
              <div className={styles.livroExplicacao}>
                <p>
                  Publique conosco seu artigo ou parecer. <br />
                  Queremos difundir novas ideias e pensamentos.
                </p>
              </div>
              <Button
                title="Publicar agora!"
                onClick={() => push("/contato")}
                color="blue"
              />
            </div>
            <div className={styles.rightSide}>
              <Image
                width={307.71}
                height={307.71}
                src={"/images/agenda/p1.webp"}
                alt="Exemplo do com a foto do autor com o periódico publicado "
                className={"imgOnHover"}
              />
              <Image
                width={307.71}
                height={307.71}
                src={"/images/agenda/p2.webp"}
                alt="Capa do periódico públicado. SLC - Solução em Licitações e Contratos"
                className={"imgOnHover"}
              />
              <Image
                width={307.71}
                height={307.71}
                src={"/images/agenda/p3.webp"}
                className={"imgOnHover"}
                alt="Exemplo de capa de um perídico mostrando soluções autorais"
              />
              <Image
                width={307.71}
                height={307.71}
                className={"imgOnHover"}
                src={"/images/agenda/p4.webp"}
                alt="Exemplo do com a foto do autor com o periódico publicado"
              />
            </div>
          </div>
        </section>
      </div>

      <FooterCompleto />
    </main>
  );
}
