import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import styles from "@/styles/SolucoesInovadoras.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";
import { useRouter } from "next/router";
import Button from "@/components/Button";
import { CursosTreinamentosType } from "@/typings/CursosTreinamentos";
import { InfoOrientacoes } from "@/utils/orientacoes";

export default function SolucoesInovadoras() {
  const { push } = useRouter();
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [modalContent, setModalContent] = useState<CursosTreinamentosType>();

  function modalState(content: CursosTreinamentosType) {
    setIsModalOpen(!isModalOpen);
    setModalContent(content)
  }

  return (
    <div className={styles.main}>
      <Head>
        <title>SGP - Soluções em Gestão Público</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.content}>
        <div className={styles.bluredBall}></div>
        <div className={styles.headerContent}>
          <h1>Orientações SGP</h1>
          <hr />
          <p>
          A Orientação SGP ampliou sua área de atuação. Agora são três Consultorias pelo preço de uma.
          </p>

          <div className={styles.buttonFrase}>
            <b>Tradicional, tributário e RH | DP | eSocial</b>
            <Button color="blue" title="Saber Mais!" />

          </div>
        </div>
      </div>
      <div className={styles.pageSize}>
        {/* <ProfessoresComponent /> */}
        <div className={styles.orientacoes}>
          {InfoOrientacoes.map(({descricao, tipo, title, img}) => (
            <div key={descricao} style={{backgroundImage: `url(${img})`}} className={styles.orientacao}>
              <div className={styles.headerTipos}>
                {tipo.map((x, index) => (
                    <span key={index}>{x}</span>
                  )
                )}
              </div>
              <div className={styles.descricao}>
                <h2>{title}</h2>
                <p>{descricao}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
      <div className={styles.image}></div>

      <FooterCompleto />
      

    </div>
  );
}