import Head from "next/head";
import React, { useState } from "react";
import Navbar from "@/components/Navbar";
import styles from "@/styles/SolucoesInovadoras.module.scss";
import { FooterCompleto } from "@/components/FooterCompleto";
import { useRouter } from "next/router";
import Button from "@/components/Button";
import { CursosTreinamentosType } from "@/typings/CursosTreinamentos";
import { InfoOrientacoes } from "@/utils/orientacoes";
import { TiposOrientacoes } from "@/utils/tipos-orientacoes";
import { AiOutlineCheckCircle } from "react-icons/ai";
import Image from "next/image";

export default function SolucoesInovadoras() {
  const { push } = useRouter();
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);
  const [modalContent, setModalContent] = useState<CursosTreinamentosType>();

  function modalState(content: CursosTreinamentosType) {
    setIsModalOpen(!isModalOpen);
    setModalContent(content)
  }

  return (
    <div className={styles.main}>
      <Head>
        <title>SGP - Soluções em Gestão Público</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <section className={styles.content}>
        <div className={styles.bluredBall}></div>
        <div className={styles.headerContent}>
          <h1>Orientações SGP</h1>
          <hr />
          <p>
          A Orientação SGP ampliou sua área de atuação. Agora são três Consultorias pelo preço de uma.
          </p>

          <div className={styles.buttonFrase}>
            <b>Tradicional, tributário e RH | DP | eSocial</b>
            <Button color="blue" title="Saber Mais!" />

          </div>
        </div>
      </section>
      <section className={styles.pageSize}>
        {/* <ProfessoresComponent /> */}
        <div className={styles.orientacoes}>
          {InfoOrientacoes.map(({descricao, tipo, title, img}) => (
            <div key={descricao} style={{backgroundImage: `url(${img})`}} className={styles.orientacao}>
              <div className={styles.headerTipos}>
                {tipo.map((x, index) => (
                    <span key={index}>{x}</span>
                  )
                )}
              </div>
              <div className={styles.descricao}>
                <h2>{title}</h2>
                <p>{descricao}</p>
              </div>
            </div>
          ))}
        </div>
      </section>
      <section className={styles.image}></section>
      <section className={styles.topicosOrientacoes}>
        <div className={styles.header}>
          <h1>Orientação SGP Tradicional</h1>
          <p>Atuante na área do Direito Administrativo e Direito Municipal.</p>
          <hr />
        </div>
        <div className={styles.fullLista}>
          {TiposOrientacoes.map((x, i) => (
            <ul className={styles.topicosLista}>
              <li className={styles.listaInterna}>
                {x.map((x) => (

                  <p><AiOutlineCheckCircle />{x}</p>
                ))}  
              </li>
            </ul>
          ))}
        </div>
      </section>
      <section className={styles.orientacoesTributarias}>
        <div className={styles.orientacaoSGPTributaria}>
            <div className={styles.textos}>
              <hr />
              <h1>Orientação SGP Tributária</h1>
              <p>Atuante na área do Direito Tributário em geral (inclusive impostos, taxas e contribuições, nos âmbitos municipal, estadual e federal.</p>
              <Button color="darkBlue" title="Envie sua solicitação"/>
            </div>
          <div className={styles.img}>
            <Image src="/images/solucoes-inovadoras/tres-maos.webp" width={593} height={385} alt="Três mãos. Uma delas digitando em um notebook cinza, outra escrevendo em uma prancheta e a última está escrevendo e digitando" />
          </div>
        </div>
        <div className={styles.orientacaoSGPTributaria}>
          <div className={styles.img}>
            <Image src="/images/solucoes-inovadoras/pessoas-discutindo.webp" width={592} height={384} alt="Três mãos. Uma delas digitando em um notebook cinza, outra escrevendo em uma prancheta e a última está escrevendo e digitando" />
          </div>
          <div className={styles.textos}>
            <hr />
            <h1>Orientação SGP RH | DP | eSocial</h1>
            <p>Atuante nas áreas de Recursos Humanos, Departamento Pessoal e eSocial.</p>
            <Button color="darkBlue" title="Envie sua solicitação"/>
          </div>
        </div>
      </section>

      <section className={styles.assesoriaJuridicaInLoco}>
        <div className={styles.texto}>
          <hr />
          <h1>Assessoria Jurídica <em>In Loco</em></h1>
          <p>Fazemos visitações no órgão ou entidade, a fim de realizar um assessoramento pessoal e diferenciado, exclusivamente na área de licitações e contratos.</p>
          <p>Num atendimento totalmente personalizado e exclusivo, nosso Corpo Jurídico, com toda sua expertise, poderá fazer quantas visitações forem necessárias para atender às suas necessidades administrativas.</p>
        </div>
      </section>

      <FooterCompleto />
      

    </div>
  );
}